routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function (){


    Route::resource('applicants','ApplicantsController');

   // Route::get ('admission','AdmissionController');

    Route::get('/admission/login', 'HomeController@login')->name('login');



     Route::post('/SendSMS/{id}', 'SendSMSController@sendMessage')->name('sendMessage');
   // Route::post('/admission/{$applicantid}', 'AdmissionController@CheckCredentials')->name('CheckCredentials');
    Route::post('/admission/{$applicantid}', 'SendSMSController@CheckCredentials')->name('CheckCredentials');


});

app/Models/Applicant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Applicant extends Model
{
    //

    protected $fillable =[
        'surname',
        'first_name',
        'other_name',
        'dob',
        'contact',
        'postal_address',
        'residence',
        'serialnumber',
        'pincode',
        'user_id',
    ];

   /* public function ApplicantAuth()
    {
        return $this->belongsTo('App\Models\ApplicantAuth');
    }*/


    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/ApplicantsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Applicant;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ApplicantsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        if(Auth::check())
        {

            $applicants = Applicant::all();

            return view('applicants.index',['applicants' => $applicants]);


        }

        return view('auth.login');


       }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        if(Auth::check())
        {


            return view('Applicants.create');

        }

        return view('auth.login');


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        if(Auth::check())
        {


            //Generate Random Number
            do{

               // echo rand(1000000,90000000);
               // $randomString = str_random(2).rand().str_random(2);

                $serialnumber =  rand(1000000,90000000);
                $rand_serial =  "PUC".$serialnumber;

                $pincode =  rand(1000,9000);
                $rand_pin =  $pincode;
            }while(!empty(Applicant ::where('serialnumber',$rand_serial)->first()));




          /*  $Clients = new clients ;
            $Clients ->name = $request->name;
            $Clients ->client_number = $rand;
            $Clients ->save();*/

            $applicant= Applicant::create([
                'surname' => $request->input('surname'),
                'first_name' => $request->input('firstname'),
                'other_name' => $request->input('othername'),
                'dob' => $request->input('dob'),
                'contact' => $request->input('contact'),
                'postal_address' => $request->input('postal_address'),
                'residence' => $request->input('residence'),
                    'serialnumber' => $rand_serial,
                    'pincode' => $rand_pin,
                'user_id' => Auth::user()->id

            ]);


            if($applicant)
            {
              // return redirect()->route('applicants.show',['company'=>$applicant->id])

                return redirect()->route('applicants.index')
                 ->with('success','Applicants created successfully');
            }
        }

        return back()->withInput()->with('errors','Error creating new Applicants');



    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Applicant  $applicant
     * @return \Illuminate\Http\Response
     */
 /*   public function show(Applicant $applicant)
    {
        //

       // $applicant = Applicant::where('id',$applicant);

        if(Auth::check())
        {


            $applicantid = $applicant::find($applicant->id);

          return view('Applicants.show',['applicant'=>$applicantid]);

        }

        return view('auth.login');

    }*/

    public function show(Applicant $applicant)
    {
        //

        if(Auth::check())
        {


            $applicant = $applicant::find($applicant->id);

            echo ($applicant->id);



            return view('Applicants.show',['applicant'=>$applicant]);

        }

        return view('auth.login');

    }














    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Applicant  $applicant
     * @return \Illuminate\Http\Response
     */
    public function edit(Applicant $applicant)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Applicant  $applicant
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Applicant $applicant)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Applicant  $applicant
     * @return \Illuminate\Http\Response
     */
    public function destroy(Applicant $applicant)
    {
        //
    }


}

resources/views/Applicants/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">

            <div class="card-body">
                <form method="POST" action="{{route('applicants.store')}}">
                    @csrf

                    <div class="form-group row">
                        <label for="site" class="col-md-4 col-form-label text-md-right">{{ __('Surname') }}</label>

                        <div class="col-md-6">

                            <input id="surname" type="text" class="form-control "
                                   name="surname" value="" required autofocus>

                        </div>




                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                        <div class="col-md-6">

                            <input id="first_name" type="text" class="form-control "
                                   name="firstname" value="" required autofocus>


                        </div>


                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Other Name') }}</label>

                        <div class="col-md-6">


                            <input id="other_name" type="text" class="form-control "
                                   name="othername" value="" required autofocus>


                        </div>


                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Date Of Birth') }}</label>

                        <div class="col-md-6">


                            <input id="dob" type="date" class="form-control "
                                   name="dob" value="" required autofocus>

                        </div>


                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Contact') }}</label>

                        <div class="col-md-6">


                            <input id="contact" type="text" class="form-control "
                                   name="contact" value="" required autofocus>

                        </div>


                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Residence') }}</label>

                        <div class="col-md-6">


                            <input id="residence" type="text" class="form-control "
                                   name="residence" value="" required autofocus>

                        </div>


                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Postal Address') }}</label>

                        <div class="col-md-6">


                            <input id="postal_address" type="text" class="form-control "
                                   name="postal_address" value="" required autofocus>



                        </div>



                    </div>





                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Save') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Applicants/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-12 col-lg-12 col-md-offset-3 col-lg-offset-3">


        <div class="card card-primary" >



            <div class="card-body">




                <table class="table table-bordered">
                    <thead>
                    <th>Surname</th>
                    <th>FirstName</th>
                    <th>OtherName</th>
                    <th>Contact</th>
                    <th>Serial Number</th>
                    <th>Pin Code</th>
                    </thead>
                    <tbody>
                    @foreach($applicants as $applicant)
                        <tr>
                            <td>{{$applicant->surname}}</td>
                            <td>{{$applicant->first_name}}</td>
                            <td>{{$applicant->other_name}}</td>
                            <td>{{$applicant->contact}}</td>
                            <td>{{$applicant->serialnumber}}</td>
                            <td>{{$applicant->pincode}}</td>
                            <td>

                                <a href="/applicants/{{$applicant->id}}" class="btn btn-link my-1"><i class="fa fa-pencil"></i>Send PinCode</a>
                                <a href="" class="btn btn-success my-1"><i class="fa fa-pencil"></i>Edit</a>
                                <a href="" class="btn btn-danger my-1"><i class="fa fa-trash"></i>Delete</a>



                                {{--       <a href="{{URL::to('department/'.$department->department_id)}}" class="btn btn-success my-1"><i class="fa fa-pencil"></i>Edit</a>
                                       <a href="{{URL::to('department/'.$department->department_id.'/delete')}}" class="btn btn-danger my-1"><i class="fa fa-trash"></i>Delete</a>--}}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>



            </div>



        </div>


    </div>

@endsection

resources/views/Applicants/pincode.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-9 col-lg-9 col-md-offset-3 col-lg-offset-3">



        <div class="card card-primary" >


        </div>

    </div>

@endsection

resources/views/Applicants/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">

        <form method="POST"  action="{{ URL::to('SendSMS') }}/{{$applicant->id }}">
            @csrf


            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Serial Number') }}</label>

                <div class="col-md-6">

                    <h1 class="display-3">{{$applicant->surname}}</h1>



                    <h1 name="serialnumber">
                    Serial Number
                    </h1>

                    <h1 name="serialnumber">
                        {{$applicant->serialnumber}}
                    </h1>



                </div>


            </div>


            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-success">
                        {{ __('Send Code') }}
                    </button>
                </div>
            </div>
        </form>



    </div>

@endsection